### ISSUE TITLE
Add support for more gampads

### ISSUE THREAD

**Issue by djsmax** [Electric1447/1Controller#2]
Hi, and first, thanks for such a great module!
However, it looks like some products (controllers) are missing.
What I did was - [I made a fork](https://github.com/djsmax/OneController), and changed some things:

- I found that some product names do not match - for example, `045e_02d1` has a name "XBox 360 USB Controller", however, relying on the source belove, it must be the one from XBox One.
- According to that USB ids source again, I added some more products - one more for One, one for the Wireless Adapter (for Windows) of Xbox 360, and also one Dongle more.
- I also added the `045e_0719`, which is another id for Wireless Receiver, and that is what I have at home so I could throughly test it. **Now it works**!

You can check it in my commits history, I think that's the case when code says more than words 😄 
I used a list of USB vendors and products and their ids from Linux USB project: [http://www.linux-usb.org/usb.ids](http://www.linux-usb.org/usb.ids)
Also to be double sure, I used a second list with all MS USB-connectable deivces: [https://www.the-sz.com/products/usbid/index.php?v=0x045E](https://www.the-sz.com/products/usbid/index.php?v=0x045E)

And what is important: the only device I have at hand, as I said above, is this Receiver for 360, so **I didn't check all other devices.** 
But looking at the names, I don't think there are so many differences between them.
Maybe on some devices will still be something like "buttons mixed up" or some time it might come to the situation like "guys, a D-Pad doesn't work on this thing" or any other kind of issues, but with these improvments other users can discover that their controllers or connectors or adapters can be supported - I think that's the aim of **1Controller** :)

**Comment by Electric1447** [comment]
Your changes have been merges.

Thanks :)
