### ISSUE TITLE
Orange Pi 5 Plus, please help me :(((( 

### ISSUE THREAD

**Issue by InfernalWolf666** [Electric1447/1Controller#9]
Hello ! I use a single board computer Orange Pi 5 plus.
[http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-plus.html](url)

I installed android 12
[https://drive.google.com/drive/folders/1rTOnBuTJA8k8ip1chh_EtnA6zz6c0UZL](url)

I connect my dualsense gamepad from Playstation 5. And it doesn’t work

I install magisk app and it can't get root access :((((

But even so, can I install the modules?
But I don’t understand which file from “1controller” should be used?

Tell me what file should I use or what folder should I use?

Help me please

**Comment by Electric1447** [comment]
You need to root with magisk, simply installing the magisk app doesn't root the device.

Then install the module as a zip.
